# fly.toml app configuration file generated for zzzcrafter on 2023-08-06T15:47:36+09:00

app = "zzzcrafter"
primary_region = "nrt"

[build]
  local = true
  builtin = "ruby"

[build.args]
  RUBY_VERSION = "3.0.2" 

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app", "cron"]

[processes]
  app = ""
  cron = "cron -f" 
